package dz.nier.autre.request;

public enum RequestValue {
	OK, CONNECT, CONNECTED, DESCONECT, DESCONNECTED, ERREUR, CONNECTION_MOMBRE, CONNECTION_ANONYME, DESCONNECT_DISTRIBUTTEUR, INSCRIPTION, CREATION_SALON, CONNECTION_SALON, REFRESH_SALON_LIST, SUPPRIMER_SALON, REFRESH_INFORMATION, ENVOI_MESSAGE;
}
