package dz.nier.autre.request;

public enum RequestKeys {
	RAISON, TYPE, ERREUR, HISTORY, MESSAGE, REPENCE, SALON_PUBLIC, SALON_PRIVEE, MOMBRES_EN_LIGNES, PSEUDO, PASSWD, NOM, PRENOM, SUJET, AUTEUR, CLIENT, SALON, DATE, NOM_CREATEUR, DISTRIBUTEUR_OUT_ID, OUT_ID, IN_ID, ACTIVITE, MOMBRE_EN_LIGNE;
}
